
import Typography from "@mui/material/Typography";
import type { NextPage } from "next";
import Head from "next/head";
import { useProducts } from "../hooks";
import { ShopLayout } from "./../components/layout";
import { ProductList } from "../components/products";
import FullScreenLoading from "../components/ui/FullScreenLoading";
import { initialData } from './../database/products';

const Home: NextPage = () => {

  const { products, error, isLoading } = useProducts('/products')
  if (isLoading) return <FullScreenLoading />;

  return (
    <div>
      <Head>
        <title>Teslo shop</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <ShopLayout
        title='Teslo-shop - Home'
        pageDescription='Encuentra los mejores productos de Teslo aqui!'
      >
        <Typography variant='h1' component='h1'>
          Tienda
        </Typography>
        <Typography variant='h2' sx={{ mb: 1 }}>
          Todos los productos
        </Typography>
        <ProductList products={products} />
      </ShopLayout>
    </div>
  );
};

export default Home;

